export const COMPLAINTS_DEF = [
  {
    id: 'fever',
    label: 'Fever',
    color: 'orange',
    onsetOptions: ['Sudden / Abrupt', 'Gradual / Slow'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '4 - 7 days' },
      { label: '1 - 2 weeks' },
      { label: '> 2 weeks', flag: 'Mandatory Tuberculosis Screening Protocol required', flagLevel: 'warning' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Active, performing daily chores/play' },
      { label: 'Moderate', description: 'Fatigued, resting, but responsive' },
      { label: 'Severe', description: 'Lethargic, bedridden, or crying inconsolably' },
    ],
    symptoms: [
      'Chills / severe shivering',
      'Pulsating, severe headache',
      'Severe muscle, bone, or joint pain',
      'Photophobia (inability to tolerate bright light)',
      'Bleeding from gums, nose, or skin lesions',
      'Neck stiffness or pain on bending head forward',
      'Altered sensorium, confusion, or giddiness',
    ],
  },
  {
    id: 'cough',
    label: 'Cough',
    color: 'orange',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '4 - 7 days' },
      { label: '1 - 2 weeks' },
      { label: '> 2 weeks', flag: 'Mandatory Tuberculosis Sputum Test required', flagLevel: 'warning' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Occasional cough, does not affect sleep or speech' },
      { label: 'Moderate', description: 'Frequent cough, limits talking in full sentences' },
      { label: 'Severe', description: 'Choking fits, unable to talk, or causing vomiting' },
    ],
    symptoms: [
      'Dry cough',
      'Cough with sputum (White)',
      'Cough with sputum (Yellow or Green)',
      'Blood in sputum / coughing up blood',
      'Wheezing or whistling sound while breathing',
      'Chest pain during coughing',
      'Night sweats',
      'Unexplained weight loss',
    ],
  },
  {
    id: 'soreThroat',
    label: 'Sore Throat',
    color: 'orange',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '4 - 7 days' },
      { label: '> 7 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Slight irritation or tickle' },
      { label: 'Moderate', description: 'Painful to swallow solid foods' },
      { label: 'Severe', description: 'Inability to swallow liquids or saliva, breathing difficulty' },
    ],
    symptoms: [
      'Pain or difficulty while swallowing',
      'Hoarseness or loss of voice',
      'Swollen or painful glands in the neck',
      'Runny nose or nasal congestion',
      'Ear pain on the same side',
    ],
  },
  {
    id: 'diarrhoea',
    label: 'Diarrhoea (Loose Stools)',
    color: 'teal',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '4 - 7 days' },
      { label: '1 - 2 weeks' },
      { label: '> 2 weeks' },
    ],
    severityOptions: [
      { label: 'Mild', description: '< 3 loose stools in a day' },
      { label: 'Moderate', description: '3 - 8 loose stools in a day with thirst' },
      { label: 'Severe', description: '> 8 loose stools, lethargic, or unable to drink' },
    ],
    symptoms: [
      'Watery, clear stools',
      'Stool containing blood or mucus',
      'Dry mouth / sunken eyes / extreme thirst',
      'Decreased urination (no urine passed in > 8 hours)',
      'Dizziness or giddiness when standing up',
    ],
  },
  {
    id: 'vomiting',
    label: 'Vomiting',
    color: 'teal',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '4 - 7 days' },
      { label: '> 7 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: '1 - 2 episodes a day, tolerating oral fluids' },
      { label: 'Moderate', description: '3 - 5 episodes, struggling to keep fluids down' },
      { label: 'Severe', description: 'Constant vomiting, completely unable to tolerate any oral intake' },
    ],
    symptoms: [
      'Nausea',
      'Yellowish discoloration of eyes or skin (Jaundice)',
      'Sunken eyes / dry tongue / no urination',
      'Vomiting blood or dark brown "coffee-ground" material',
      'Preceded by a head injury or trauma',
    ],
  },
  {
    id: 'abdominalPain',
    label: 'Abdominal Pain',
    color: 'teal',
    onsetOptions: ['Sudden / Abrupt (onset within minutes)', 'Gradual / Slow'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '4 - 7 days' },
      { label: '> 7 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Bothersome but able to walk and work' },
      { label: 'Moderate', description: 'Forces patient to lie down, limits physical activity' },
      { label: 'Severe', description: 'Agonizing pain, crying, unable to stand or allow abdomen to be touched' },
    ],
    symptoms: [
      'Pain localized to the lower-right side',
      'Burning pain in upper-middle stomach',
      'Swollen, distended, or hard abdomen',
      'Vomiting or nausea',
      'Diarrhea or constipation',
      'Blood in stool or black tarry stools',
      'Pain worse after eating fatty/greasy food',
      'Pain relieved completely after passing gas or stools',
    ],
  },
  {
    id: 'chestPain',
    label: 'Chest Pain',
    color: 'red',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 15 minutes' },
      { label: '15 - 30 minutes' },
      { label: '30 minutes to 3 hours' },
      { label: '> 3 hours', flag: 'Possible Cardiac ACS — Immediate referral may be required', flagLevel: 'critical' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Dull ache or brief discomfort' },
      { label: 'Moderate', description: 'Heavy pressure or squeezing sensation' },
      { label: 'Severe', description: 'Crushing pain, feeling of "an elephant sitting on the chest"' },
    ],
    symptoms: [
      'Pain radiates to jaw, neck, left arm, shoulder, or back',
      'Accompanied by profuse sweating (cold sweat) and pallor',
      'Severe shortness of breath or choking feeling',
      'Nausea, vomiting, or indigestion-like feeling',
      'Palpitations (fast, thumping heartbeat)',
      'Pain worsens with physical exertion and is relieved by rest',
      'Pain worsens with deep breathing, coughing, or pressing on the chest wall',
    ],
    symptomFlags: {
      'Pain radiates to jaw, neck, left arm, shoulder, or back': { message: 'Cardiac ACS Risk — Emergency referral may be needed', level: 'critical' },
    },
  },
  {
    id: 'sob',
    label: 'Shortness of Breath',
    color: 'red',
    onsetOptions: ['Sudden / Instantaneous', 'Gradual'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '4 - 7 days' },
      { label: '> 7 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Occurs only with moderate physical exertion' },
      { label: 'Moderate', description: 'Occurs during light walking; speaks in broken sentences' },
      { label: 'Severe', description: 'Struggling to breathe at rest; gasping; speaks only single words' },
    ],
    symptoms: [
      'Wheezing, whistling, or rattling sounds from chest',
      'Cough with yellow/green phlegm or blood',
      'Swelling in both ankles or feet (pedal edema)',
      'Chest pain or chest tightness',
      'Bluish color of lips, face, or fingernails (Cyanosis)',
      'Worse when lying flat on back (requires propping up with pillows)',
    ],
    symptomFlags: {
      'Bluish color of lips, face, or fingernails (Cyanosis)': { message: 'Cyanosis detected — Emergency evaluation needed', level: 'critical' },
    },
  },
  {
    id: 'headache',
    label: 'Headache',
    color: 'red',
    onsetOptions: ['Sudden (Worst headache of life, "thunderclap" onset)', 'Gradual'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '4 - 7 days' },
      { label: '> 7 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Dull, background ache, daily activities unaffected' },
      { label: 'Moderate', description: 'Throbbing, limits work or study concentration' },
      { label: 'Severe', description: 'Incapacitating, must lie down in a dark room' },
    ],
    symptoms: [
      'Extreme sensitivity to light (photophobia)',
      'Neck stiffness (unable to touch chin to chest)',
      'Nausea or projectile vomiting',
      'Blurring of vision or double vision',
      'Sudden weakness or numbness in face, arm, or leg',
      'Confusion, slurred speech, or loss of balance',
    ],
    symptomFlags: {
      'Extreme sensitivity to light (photophobia)': { message: 'KFD / Meningitis Alert — Evaluate immediately', level: 'critical' },
      'Neck stiffness (unable to touch chin to chest)': { message: 'Meningitis Flag — Immediate evaluation needed', level: 'critical' },
      'Sudden weakness or numbness in face, arm, or leg': { message: 'Stroke Alert — Emergency referral needed', level: 'critical' },
    },
  },
  {
    id: 'giddiness',
    label: 'Giddiness / Dizziness',
    color: 'purple',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '> 3 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Lightheadedness, passing feeling of instability' },
      { label: 'Moderate', description: 'Feeling that the room is spinning (vertigo), unsteady gait' },
      { label: 'Severe', description: 'Unable to stand, leading to falls or brief loss of consciousness' },
    ],
    symptoms: [
      'Feeling of spinning (Vertigo)',
      'Ringing sound in ears (Tinnitus)',
      'Temporary loss of consciousness or fainting (Syncope)',
      'Palpitations or chest pain',
      'Pale skin, lips, or inner eyelids',
      'Numbness, weakness, or tingling on one side of body',
      'Occurs primarily when standing up suddenly',
    ],
    symptomFlags: {
      'Pale skin, lips, or inner eyelids': { message: 'Anemia Alert — Check pallor, consider referral', level: 'warning' },
      'Numbness, weakness, or tingling on one side of body': { message: 'Possible Stroke/TIA — Urgent evaluation needed', level: 'critical' },
    },
  },
  {
    id: 'weakness',
    label: 'Generalized Weakness / Fatigue',
    color: 'purple',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 3 days' },
      { label: '4 - 7 days' },
      { label: '1 - 2 weeks' },
      { label: '> 2 weeks' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Tired but manages standard household/farm work' },
      { label: 'Moderate', description: 'Frequently needs to lie down during the day' },
      { label: 'Severe', description: 'Bedbound, completely unable to perform basic self-care' },
    ],
    symptoms: [
      'Pale inner eyelids and palms (pallor)',
      'Shortness of breath during light tasks',
      'Fever or chills',
      'Rapid weight loss or loss of appetite',
      'Swelling in feet or face',
      'Severe muscle pain or body aches',
      'Yellowing of eyes (Jaundice)',
    ],
    symptomFlags: {
      'Pale inner eyelids and palms (pallor)': { message: 'Severe Anemia Flag — Immediate evaluation needed', level: 'critical' },
    },
  },
  {
    id: 'bodyAches',
    label: 'Body Aches / Muscle / Joint Pain',
    color: 'blue',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 3 days' },
      { label: '4 - 7 days' },
      { label: '1 - 2 weeks' },
      { label: '> 2 weeks' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Aching but mobile and working' },
      { label: 'Moderate', description: 'Stiffness, limits walking and bending' },
      { label: 'Severe', description: 'Joints locked, severe muscle pain, unable to move' },
    ],
    symptoms: [
      'Swelling, redness, or warmth in one or more joints',
      'Severe low back pain or neck pain',
      'Fatigue or generalized weakness',
      'Headaches',
      'Morning stiffness lasting more than 30 minutes',
    ],
    hasJointsField: true,
  },
  {
    id: 'skinRash',
    label: 'Skin Rash / Itching / Ulcer',
    color: 'blue',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 3 days' },
      { label: '4 - 7 days' },
      { label: '1 - 2 weeks' },
      { label: '> 2 weeks' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Local irritation, no pain or sleep disruption' },
      { label: 'Moderate', description: 'Severe itching, scratch marks, minor pain' },
      { label: 'Severe', description: 'Extremely painful, fluid leaking, skin peeling off, or non-healing ulcer' },
    ],
    symptoms: [
      'Itchy, ring-like circular patches',
      'Red or dark skin patch with loss of sensation to touch',
      'Fluid-filled blisters or pus-filled pockets',
      'Rash spreads rapidly across the whole body',
      'Fever accompanied by rash',
      'Chronic non-healing ulcer on foot or leg (especially in diabetic patients)',
    ],
  },
  {
    id: 'eyeRedness',
    label: 'Eye Redness / Discharge',
    color: 'blue',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 3 days' },
      { label: '4 - 7 days' },
      { label: '> 7 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Redness only' },
      { label: 'Moderate', description: 'Itching, pain, gritty feeling' },
      { label: 'Severe', description: 'Thick pus, eyelids stuck, vision loss' },
    ],
    symptoms: [
      'Thick, yellow/green discharge (pus)',
      'Swelling of eyelids',
      'Blurring of vision or decrease in vision',
      'Extreme pain or burning sensation in the eye',
      'Intense itching or watery eyes',
    ],
  },
  {
    id: 'earPain',
    label: 'Ear Pain / Discharge',
    color: 'blue',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 3 days' },
      { label: '4 - 7 days' },
      { label: '> 7 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Occasional ache' },
      { label: 'Moderate', description: 'Constant pain, affects concentration' },
      { label: 'Severe', description: 'Throbbing, unbearable pain, fever' },
    ],
    symptoms: [
      'Discharge of fluid, yellow pus, or foul-smelling liquid',
      'Bleeding from the ear',
      'Hearing loss or muffled hearing',
      'Swelling or tenderness behind the ear',
      'Ringing sound in the ear',
    ],
  },
  {
    id: 'urination',
    label: 'Painful / Burning / Difficult Urination',
    color: 'teal',
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '4 - 7 days' },
      { label: '> 7 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Slight sting' },
      { label: 'Moderate', description: 'Strong burning sensation' },
      { label: 'Severe', description: 'Inability to pass urine despite urge' },
    ],
    symptoms: [
      'Passing urine very frequently in small amounts',
      'Blood in urine (pink, red, or cloudy urine)',
      'Lower back pain or pain in the side (flank)',
      'High fever with chills',
      'Foul-smelling or dark urine',
      'Lower abdominal pain',
    ],
  },
  {
    id: 'wound',
    label: 'Wound / Injury / External Bleeding',
    color: 'red',
    onsetOptions: ['Sudden (Immediate consequence of trauma/injury)'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '> 3 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Scrapes, minor bruises' },
      { label: 'Moderate', description: 'Deep cut, bleeding controlled with pressure' },
      { label: 'Severe', description: 'Uncontrolled bleeding, visible bone/muscle, or head injury with confusion' },
    ],
    symptoms: [
      'Active, continuous bleeding',
      'Severe pain or inability to move the affected limb',
      'Swelling, bruising, or deformity in the injured area',
      'Post-injury vomiting, drowsiness, or loss of memory',
      'Wound is hot, red, swollen, or discharging pus',
      'Fever',
    ],
    symptomFlags: {
      'Post-injury vomiting, drowsiness, or loss of memory': { message: 'Head Injury Warning — Immediate evaluation needed', level: 'critical' },
      'Wound is hot, red, swollen, or discharging pus': { message: 'Infection Flag — Monitor closely, consider antibiotics', level: 'warning' },
    },
  },
  {
    id: 'animalBite',
    label: 'Animal / Insect / Tick Bite',
    color: 'red',
    onsetOptions: ['Sudden (Known bite occurrence)'],
    durationOptions: [
      { label: '< 24 hours' },
      { label: '1 - 3 days' },
      { label: '> 3 days' },
    ],
    severityOptions: [
      { label: 'Mild', description: 'Local itch/redness' },
      { label: 'Moderate', description: 'Severe swelling/pain' },
      { label: 'Severe', description: 'Difficulty breathing, muscle weakness, systemic bleeding' },
    ],
    symptoms: [
      'Bite from a snake (fang marks, progressive numbness, paralysis, bleeding)',
      'Bite from a dog, cat, or monkey (torn skin, bleeding)',
      'Bite from a tick / recent forest visits',
      'Swelling of lips, tongue, or face',
      'Breathing difficulty, wheezing, or throat tightness',
      'Drooling or inability to swallow saliva',
    ],
    symptomFlags: {
      'Bite from a snake (fang marks, progressive numbness, paralysis, bleeding)': { message: 'Snakebite — Emergency protocol required immediately', level: 'critical' },
      'Bite from a dog, cat, or monkey (torn skin, bleeding)': { message: 'Rabies exposure — Anti-rabies treatment required urgently', level: 'critical' },
    },
  },
  {
    id: 'other',
    label: 'Any Other Complaint',
    color: 'gray',
    isOpenEnded: true,
    onsetOptions: ['Sudden', 'Gradual'],
    durationOptions: [
      { label: '< 3 days' },
      { label: '4 - 7 days' },
      { label: '1 - 2 weeks' },
      { label: '> 2 weeks' },
    ],
    severityOptions: [
      { label: 'Mild' },
      { label: 'Moderate' },
      { label: 'Severe' },
    ],
    symptoms: [],
  },
]

export const COMPLAINT_COLOR_MAP = {
  orange: { bg: 'bg-orange-50', border: 'border-orange-200', text: 'text-orange-700', badge: 'bg-orange-100 text-orange-700', selected: 'bg-orange-100 border-orange-400' },
  teal:   { bg: 'bg-teal-50',   border: 'border-teal-200',   text: 'text-teal-700',   badge: 'bg-teal-100 text-teal-700',   selected: 'bg-teal-100 border-teal-400' },
  red:    { bg: 'bg-red-50',    border: 'border-red-200',    text: 'text-red-700',    badge: 'bg-red-100 text-red-700',    selected: 'bg-red-100 border-red-400' },
  purple: { bg: 'bg-purple-50', border: 'border-purple-200', text: 'text-purple-700', badge: 'bg-purple-100 text-purple-700', selected: 'bg-purple-100 border-purple-400' },
  blue:   { bg: 'bg-blue-50',   border: 'border-blue-200',   text: 'text-blue-700',   badge: 'bg-blue-100 text-blue-700',   selected: 'bg-blue-100 border-blue-400' },
  gray:   { bg: 'bg-gray-50',   border: 'border-gray-200',   text: 'text-gray-700',   badge: 'bg-gray-100 text-gray-700',   selected: 'bg-gray-100 border-gray-400' },
}
